name: assignment
channels:
  - defaults
  - conda-forge
  - udst
dependencies:
  - ipython=7.11.1
  - matplotlib=3.1.3
  - notebook=6.0.1
  - numpy=1.18.1
  - pandas=1.0.1
  - tqdm
  - plotly=4.5.0
  - pyqt=5.12.3
  - pysal=2.1.0
  - pyshp=2.1.0
  - scipy=1.3.2
  - dill=0.3.1.1
  - glob
  - xlrd=1.2.0
